# wrangler.toml
name = "moboy-post" # Pastikan nama ini sesuai
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# --- INI BAGIAN KRUSIAL ---
[[d1_databases]]
binding = "DB" # Nama binding ini HARUS "DB"
database_name = "db_moboy" # Ganti dengan nama database D1 Anda
database_id = "cc8b6847-ed79-46b9-ab92-dbb265ec9865" # Ganti dengan ID database D1 Anda

# Anda juga bisa menambahkan ini untuk preview environment
[[d1_databases]]
binding = "DB"
database_name = "db_moboy"
database_id = "cc8b6847-ed79-46b9-ab92-dbb265ec9865"
# preview_database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" # Jika punya DB terpisah untuk preview
