# wrangler.toml
name = "moboy-post"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# --- KONFIGURASI D1 DATABASE (HANYA SATU) ---
[[d1_databases]]
binding = "DB"
database_name = "db_moboy"
database_id = "cc8b6847-ed79-46b9-ab92-dbb265ec9865"

# --- ENVIRONMENT VARIABLES UNTUK PRODUCTION ---
[env.production.vars]
ENVIRONMENT = "production"
NEXTAUTH_URL = "https://moboy-post.pages.dev"
NEXTAUTH_SECRET = "83384eb0bd1ac0a084543b132f07b78f"
