name = "moboy-post"
compatibility_date = "2024-10-21" 
compatibility_flags = [ "nodejs_compat" ]

# 💡 Bagian ini yang krusial untuk Binding D1
[[d1_databases]]
binding = "DB"
database_name = "db_moboy"
database_id = "cc8b6847-ed79-46b9-ab92-dbb265ec9865" # Ganti dengan ID Database Anda
